// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg754Np_seH0zGtZ8O-xnXw2rWYMihV48',
    appId: '1:589255927955:web:ff16fd36f703b4f2b8c566',
    messagingSenderId: '589255927955',
    projectId: 'blocauth-3dc8c',
    authDomain: 'blocauth-3dc8c.firebaseapp.com',
    storageBucket: 'blocauth-3dc8c.appspot.com',
    measurementId: 'G-P48H162286',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH3ppJeXYPS65x261ZzuURX3tfoPPUQIE',
    appId: '1:589255927955:android:091a2efaa91203fab8c566',
    messagingSenderId: '589255927955',
    projectId: 'blocauth-3dc8c',
    storageBucket: 'blocauth-3dc8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmz3dT-Iou66iet3xoKMNQ8VfBRsvKDZo',
    appId: '1:589255927955:ios:546775c52ad33ed8b8c566',
    messagingSenderId: '589255927955',
    projectId: 'blocauth-3dc8c',
    storageBucket: 'blocauth-3dc8c.appspot.com',
    iosClientId: '589255927955-5re7n52ces5birg23chtbojji1pjbtf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.blockPattern',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmz3dT-Iou66iet3xoKMNQ8VfBRsvKDZo',
    appId: '1:589255927955:ios:546775c52ad33ed8b8c566',
    messagingSenderId: '589255927955',
    projectId: 'blocauth-3dc8c',
    storageBucket: 'blocauth-3dc8c.appspot.com',
    iosClientId: '589255927955-5re7n52ces5birg23chtbojji1pjbtf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.blockPattern',
  );
}
